services:
  biz-service:
    build:
      context: .
      dockerfile: DZ_MP_BIZ_SERVICE.API/Dockerfile
    container_name: mp_biz_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_URL};Search Path=biz
      - JwtSettings__Key=${JWT_KEY}
    ports:
      - "5004:8080"
