services:
  masterfile-service:
    build:
      context: .
      dockerfile: DZ_MP_MASTERFILE_SERVICE.API/Dockerfile
    container_name: mp_masterfile_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_URL};Search Path=system_master
      - JwtSettings__Key=${JWT_KEY}
    ports:
      - "5002:8080"

  system-mgmt-service:
    build:
      context: .
      dockerfile: DZ_MP_SYSTEM_MGMT_SERVICE.API/Dockerfile
    container_name: mp_system_mgmt_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_URL};Search Path=system_management
      - ServiceUrls__MasterService=http://masterfile-service:8080/api/v1/
      - ServiceUrls__BizService=http://biz-service:8080/api/v1/
      - JwtSettings__Key=${JWT_KEY}
    ports:
      - "5003:8080"

  biz-service:
    build:
      context: .
      dockerfile: DZ_MP_BIZ_SERVICE.API/Dockerfile
    container_name: mp_biz_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_URL};Search Path=biz
      - ServiceUrls__MasterService=http://masterfile-service:8080/api/v1/
      - JwtSettings__Key=${JWT_KEY}
    ports:
      - "5004:8080"

  log-service:
    build:
      context: .
      dockerfile: DZ_MP_LOG_SERVICE.API/Dockerfile
    container_name: mp_log_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_URL};Search Path=log
      - JwtSettings__Key=${JWT_KEY}
    ports:
      - "5005:8080"
